### ISSUE TITLE
To-do list of future bug fixes/features

### ISSUE THREAD

**Issue by WrichikBasu** [WrichikBasu/ShakeAlarmClock#19]
This issue is a to-do list of future enhancements that will be integrated into the app.

**If you have one or more feature requests, create a separate issue for each of them.**

 - [x] Change how alarms are activated after a reboot — do not activate alarms that have passed their time. (#21)
 - [x] Ask user to disable battery optimization for the app. (#21)
 - [x] Manage what will happen when an alarm triggers while another alarm is currently snoozed. (#29)
 - [ ] Work on changing time, date and time zones — support [`Intent.ACTION_TIME_CHANGED`](https://developer.android.com/reference/android/content/Intent#ACTION_TIME_CHANGED), [`Intent.ACTION_DATE_CHANGED`](https://developer.android.com/reference/android/content/Intent#ACTION_DATE_CHANGED) and [`Intent.ACTION_TIMEZONE_CHANGED`](https://developer.android.com/reference/android/content/Intent#ACTION_TIMEZONE_CHANGED).
 - [ ] Change font sizes and dimensions for tablet view.
